# Generated by Django 4.0 on 2021-12-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frontEndModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_url', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=250)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
