# Generated by Django 4.0 on 2021-12-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fullStackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_url', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=250)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mobileDevModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_url', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=250)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
