# Generated by Django 4.0 on 2021-12-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0004_alter_frontendmodel_bio_alter_frontendmodel_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendmodel',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
