# Generated by Django 4.0 on 2021-12-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0005_alter_frontendmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendmodel',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
